title: "Cybersecurity Labs by Pruthviraj"
description: "Hands-on cybersecurity experiments and write-ups. Learning by doing!"

theme: jekyll-theme-hacker

markdown: kramdown
highlighter: rouge

author:
  name: "Pruthviraj Patil"
  email: "pruthvirajpatil.info@gmail.com"
  instagram: "pruthviraj.ig"
  

show_excerpts: true
